[project]
name = "st-pydanticai-charts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "pydantic>=2.10.6",
    "pydantic-ai>=0.0.36",
    "streamlit>=1.43.1",
]
